services:
  # Since the Loki containers are running as user 10001 and the mounted data volume is owned by root,
  # Loki would not have permissions to create the directories.
  # Therefore the init container changes permissions of the mounted directory.
  init:
    image: grafana/loki:2.7.3
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/loki"
    volumes:
      - ./loki:/loki

  loki:
    image: grafana/loki:2.7.3
    volumes:
      - ./loki/:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    depends_on:
      - init
