VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos65"

  config.vm.network :forwarded_port, guest: 3000, host: 33000
  config.vm.network :forwarded_port, guest: 8080, host: 38080

  config.vm.synced_folder "C:/code", "/code"

  config.vm.provider :virtualbox do |vb|
     # Don't boot with headless mode
     # vb.gui = true
  
     # Use VBoxManage to customize the VM. For example to change memory:
     vb.customize ["modifyvm", :id, "--memory", "1536"]
     # Also making its multicore
     vb.customize ["modifyvm", :id, "--cpus", "2"]  
     vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end
end
